name: chaptify
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - kerchunk=0.2.6
  - pyyaml=6.0.2
  - xlsxwriter=3.2.0
  - openpyxl=3.1.5
  - fastparquet=2024.5.0
  - python-dotenv
  - requests
  - beautifulsoup4
  - bokeh
  - plotly
  - jupyterlab
  - pandas
  - xarray
  - zarr
  - mutagen
  - pydub
  - levenshtein
